
from django.urls import path
from .views import (
    TaskGroupListView, TaskGroupStreamView, TaskStartView, TaskDetailView,
    ResultListView, ResultUpdateView, ResultCommentView,
    FilterTaskCreateView,
    BulkFilterTaskCreateView,
    IssueProcessTaskCreateView, IssueProcessTaskDetailView,
    BulkIssueProcessTaskCreateView,
    IssueProcessResultUpdateView, IssueProcessResultCommentView,
    IssueProcessResultReviewView,
    IssueProcessResultManualReviewView,
    IssueProcessResultValidationRunCreateView,
    IssueProcessResultLatestValidationRunView,
    IssueValidationRunDetailView,
    IssueValidationRunOverrideView,
)
from .views_rule_groups import (
    FilterTaskIssueListView,
    LatestFilterTaskView,
    RuleGroupProcessedIssueJiraView,
    RuleGroupProcessedIssueDetailView,
    RuleGroupProcessedIssueListView,
    RuleGroupProcessedIssueTransitionView,
    RuleGroupDetailView,
    RuleGroupListView,
    RuleGroupStreamView,
)

urlpatterns = [
    path('tasks/groups/', TaskGroupListView.as_view(), name='task-groups'),
    path('tasks/stream/', TaskGroupStreamView.as_view(), name='task-stream'),
    path('tasks/start/', TaskStartView.as_view(), name='task-start'),
    path('tasks/<int:pk>/', TaskDetailView.as_view(), name='task-detail'),
    path('results/', ResultListView.as_view(), name='result-list'),
    path('results/<int:pk>/save/', ResultUpdateView.as_view(), name='result-save'),
    path('results/<int:pk>/comment/', ResultCommentView.as_view(), name='result-comment'),
    # 新增：规则组筛票 & 单票处理
    path('rule-groups/', RuleGroupListView.as_view(), name='rule-group-list'),
    path('rule-groups/stream/', RuleGroupStreamView.as_view(), name='rule-group-stream'),
    path('rule-groups/<int:role_index>/detail/', RuleGroupDetailView.as_view(), name='rule-group-detail'),
    path('rule-groups/<int:role_index>/processed-issues/', RuleGroupProcessedIssueListView.as_view(), name='rule-group-processed-issues'),
    path('rule-groups/<int:role_index>/processed-issues/<str:issue_key>/', RuleGroupProcessedIssueDetailView.as_view(), name='rule-group-processed-issue-detail'),
    path('rule-groups/<int:role_index>/processed-issues/<str:issue_key>/jira/', RuleGroupProcessedIssueJiraView.as_view(), name='rule-group-processed-issue-jira'),
    path('rule-groups/<int:role_index>/processed-issues/<str:issue_key>/transition/', RuleGroupProcessedIssueTransitionView.as_view(), name='rule-group-processed-issue-transition'),
    path('rule-groups/<int:role_index>/filter-tasks/', FilterTaskCreateView.as_view(), name='filter-task-create'),
    path('rule-groups/filter-tasks/bulk/', BulkFilterTaskCreateView.as_view(), name='bulk-filter-task-create'),
    path('rule-groups/<int:role_index>/filter-tasks/latest/', LatestFilterTaskView.as_view(), name='latest-filter-task'),
    path('filter-tasks/<int:pk>/issues/', FilterTaskIssueListView.as_view(), name='filter-task-issues'),
    path('filter-tasks/<int:filter_task_id>/issues/<str:issue_key>/process-tasks/', IssueProcessTaskCreateView.as_view(), name='issue-process-task-create'),
    path('rule-groups/process-tasks/bulk/', BulkIssueProcessTaskCreateView.as_view(), name='bulk-issue-process-task-create'),
    path('process-tasks/<int:pk>/', IssueProcessTaskDetailView.as_view(), name='issue-process-task-detail'),
    path('process-results/<int:pk>/', IssueProcessResultUpdateView.as_view(), name='issue-process-result-update'),
    path('process-results/<int:pk>/comment/', IssueProcessResultCommentView.as_view(), name='issue-process-result-comment'),
    path('process-results/<int:pk>/review/', IssueProcessResultReviewView.as_view(), name='issue-process-result-review'),
    path('process-results/<int:pk>/manual-review/', IssueProcessResultManualReviewView.as_view(), name='issue-process-result-manual-review'),
    path('process-results/<int:pk>/validation-runs/', IssueProcessResultValidationRunCreateView.as_view(), name='issue-process-result-validation-run-create'),
    path('process-results/<int:pk>/validation-runs/latest/', IssueProcessResultLatestValidationRunView.as_view(), name='issue-process-result-latest-validation-run'),
    path('validation-runs/<int:pk>/', IssueValidationRunDetailView.as_view(), name='issue-validation-run-detail'),
    path('validation-runs/<int:pk>/override/', IssueValidationRunOverrideView.as_view(), name='issue-validation-run-override'),
]
