# Generated by Django 5.2.13 on 2026-04-21 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Geely2AnalysisTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_key", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("RUNNING", "RUNNING"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("FETCH_COMMENTS", "FETCH_COMMENTS"),
                            ("EXTRACT_RELATED_SIGNALS", "EXTRACT_RELATED_SIGNALS"),
                            ("DOWNLOAD_ARCHIVES", "DOWNLOAD_ARCHIVES"),
                            ("UNPACK_QNX_LOG", "UNPACK_QNX_LOG"),
                            ("SELECT_TARGET_CYCLES", "SELECT_TARGET_CYCLES"),
                            ("FILTER_BOSCH_LOGS", "FILTER_BOSCH_LOGS"),
                            (
                                "EXTRACT_UPPER_REQUIREMENTS",
                                "EXTRACT_UPPER_REQUIREMENTS",
                            ),
                            ("AI_ANALYZE", "AI_ANALYZE"),
                            ("SAVE_RESULT", "SAVE_RESULT"),
                        ],
                        default="FETCH_COMMENTS",
                        max_length=64,
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True, default="")),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "workspace_dir",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geely2_analysis_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Geely2AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_key", models.CharField(max_length=64)),
                ("ai_summary", models.TextField(blank=True, default="")),
                ("reply_text", models.TextField(blank=True, default="")),
                ("evidence_payload", models.JSONField(blank=True, default=dict)),
                ("confidence", models.FloatField(default=0)),
                ("risk_notes", models.TextField(blank=True, default="")),
                ("needs_user_confirmation", models.BooleanField(default=True)),
                (
                    "comment_status",
                    models.CharField(
                        choices=[
                            ("NOT_CONFIRMED", "NOT_CONFIRMED"),
                            ("CONFIRMED_NOT_COMMENTED", "CONFIRMED_NOT_COMMENTED"),
                            ("COMMENTED", "COMMENTED"),
                            ("COMMENT_FAILED", "COMMENT_FAILED"),
                        ],
                        default="NOT_CONFIRMED",
                        max_length=32,
                    ),
                ),
                ("commented_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geely2_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "analysis_task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="geely2_analyzer.geely2analysistask",
                    ),
                ),
            ],
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Geely2IssueSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_key", models.CharField(max_length=64)),
                ("summary", models.CharField(blank=True, default="", max_length=500)),
                ("assignee", models.CharField(blank=True, default="", max_length=255)),
                ("jira_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_analysis_status",
                    models.CharField(default="IDLE", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geely2_issue_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ["issue_key"],
            },
        ),
        migrations.AddField(
            model_name="geely2analysistask",
            name="issue_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_tasks",
                to="geely2_analyzer.geely2issuesnapshot",
            ),
        ),
        migrations.CreateModel(
            name="Geely2SyncTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("RUNNING", "RUNNING"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("issue_count", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True, default="")),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geely2_sync_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="geely2issuesnapshot",
            name="last_sync_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="snapshots",
                to="geely2_analyzer.geely2synctask",
            ),
        ),
        migrations.CreateModel(
            name="JiraCredentialBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_code", models.CharField(default="geely2", max_length=32)),
                (
                    "jira_base_url",
                    models.URLField(default="https://boolbool.atlassian.net/"),
                ),
                ("jira_username", models.CharField(max_length=255)),
                ("encrypted_password", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jira_bindings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "unique_together": {("user", "project_code")},
            },
        ),
        migrations.AddField(
            model_name="geely2synctask",
            name="credential_binding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_tasks",
                to="geely2_analyzer.jiracredentialbinding",
            ),
        ),
        migrations.AddField(
            model_name="geely2analysistask",
            name="credential_binding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_tasks",
                to="geely2_analyzer.jiracredentialbinding",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="geely2issuesnapshot",
            unique_together={("user", "issue_key")},
        ),
    ]
