# Generated by Django 4.2.3 on 2026-04-20 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0002_analysistask_role_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilteredIssueSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_key", models.CharField(max_length=64)),
                ("summary", models.CharField(blank=True, default="", max_length=500)),
                ("assignee", models.CharField(blank=True, default="", max_length=200)),
                ("issue_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["issue_key"],
            },
        ),
        migrations.CreateModel(
            name="FilterTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_index", models.PositiveIntegerField(db_index=True)),
                (
                    "role_label",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("jql", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("RUNNING", "RUNNING"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILED", "FAILED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("issue_count", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IssueProcessTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_key", models.CharField(db_index=True, max_length=64)),
                ("summary", models.CharField(blank=True, default="", max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("RUNNING", "RUNNING"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("PREPARING", "PREPARING"),
                            ("DOWNLOADING", "DOWNLOADING"),
                            ("UNPACKING", "UNPACKING"),
                            ("PARSING", "PARSING"),
                            ("MODEL_INFERENCE", "MODEL_INFERENCE"),
                            ("GENERATING_REPLY", "GENERATING_REPLY"),
                            ("SAVING_RESULT", "SAVING_RESULT"),
                        ],
                        default="PREPARING",
                        max_length=40,
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "filter_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_tasks",
                        to="analyzer.filtertask",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_tasks",
                        to="analyzer.filteredissuesnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IssueProcessResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_key", models.CharField(max_length=64)),
                ("summary", models.CharField(blank=True, default="", max_length=500)),
                ("model", models.CharField(blank=True, default="", max_length=100)),
                (
                    "result_status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "SUCCESS"),
                            ("FAILED", "FAILED"),
                            ("MANUAL", "MANUAL"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("reply_text", models.TextField(blank=True, default="")),
                (
                    "can_trace_image",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "can_trace_image_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("raw_signals", models.TextField(blank=True, default="")),
                ("has_commented_to_jira", models.BooleanField(default=False)),
                ("commented_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "process_task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="analyzer.issueprocesstask",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="filteredissuesnapshot",
            name="filter_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="analyzer.filtertask",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="filteredissuesnapshot",
            unique_together={("filter_task", "issue_key")},
        ),
    ]
