# Generated by Django 5.2.13 on 2026-05-19 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0006_issuelearningmemory"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueValidationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("RUNNING", "RUNNING"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "system_verdict",
                    models.CharField(
                        choices=[
                            ("PASS", "PASS"),
                            ("FAIL", "FAIL"),
                            ("WARNING", "WARNING"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("summary_reason", models.TextField(blank=True, default="")),
                ("evidence_payload", models.JSONField(blank=True, default=dict)),
                ("chart_payload", models.JSONField(blank=True, default=dict)),
                (
                    "ruleset_version",
                    models.CharField(blank=True, default="v1", max_length=50),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "manual_verdict",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("manual_reason", models.TextField(blank=True, default="")),
                ("manual_note", models.TextField(blank=True, default="")),
                (
                    "manual_operator",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("manual_saved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "process_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_runs",
                        to="analyzer.issueprocessresult",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IssueValidationCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_type", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASS", "PASS"),
                            ("FAIL", "FAIL"),
                            ("WARNING", "WARNING"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("reason", models.TextField(blank=True, default="")),
                ("evidence_payload", models.JSONField(blank=True, default=dict)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "validation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="analyzer.issuevalidationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "unique_together": {("validation_run", "check_type")},
            },
        ),
    ]
